spring.application.name=hr-config-server
server.port=8888

## Git configuration ##
spring.cloud.config.server.git.uri=https://github.com/Bielnegri/Microservice-Course-Configs
spring.cloud.config.server.git.default-label=main
